Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
 
  # Provider-specific configuration in this Case VirtualBox
  config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      # vb.gui = true
      # Customize the amount of memory on the VM:
      vb.memory = "2048" # 2GB de RAM
      # Specify the name of the virtual machine.
      vb.name = "vm-Atenas"
  #config.vm.network "forwarded_port", guest: 80, host: 8080
  
  end

  # Enable provisioning with a shell script for Tunnel CloudFlare
  config.vm.provision "shell" do |s|
    s.path = "tunnel_CloudFlare.sh"
  end

  # Enable provisioning with a shell script for LEMP and Wordpress 
  config.vm.provision "shell" do |s|
    s.path = "provision_LEMP_Wordpress.sh"
  end

end
