
Vagrant.configure("2") do |config|
  # Debian 12 Box
  config.vm.box = "debian/bookworm64"

  # Provider-specific configuration for VirtualBox:
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
      vb.gui = true
  #   # Customize the amount of memory on the VM:
      vb.memory = "2048" # 2GB de RAM
      # Specify the name of the virtual machine.
      vb.name = "vm-Atenas"
  
  end
 
end
